[project]
name = "cosmonaut-backend"
version = "0.1.0"
description = "Cosmonaut AI backend Lambdaolith"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools[all]",
    "boto3",
    "fastapi",
    "pinecone-client",
    "pynamodb",
    "pydantic",
    "pydantic-settings",
    "pydantic-ai-slim[retries]",
    "tenacity",
    "pinecone>=8.0.0",
    "google-genai>=1.56.0",
    "pydantic-ai>=1.37.0",
    "pyjwt[crypto]>=2.10.1",
    "nest-asyncio>=1.6.0",
    "cryptography>=46.0.3",
    "uvicorn>=0.38.0",
    "stripe>=11.0.0",
]


[dependency-groups]
dev = [
    "boto3-stubs[all]>=1.42.18",
    "httpx",
    "pytest",
    "uvicorn>=0.38.0",
]

[tool.ruff]
line-length = 120
indent-width = 2
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
